from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime

async def generate_pdf_report(scan, findings, summary, target):
    """Generate a professional PDF report for a scan"""
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, 
                           rightMargin=72, leftMargin=72,
                           topMargin=72, bottomMargin=18)
    
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # Title
    story.append(Paragraph("Senpai AI Security Report", title_style))
    story.append(Spacer(1, 12))
    
    # Report Info
    info_data = [
        ["Target URL:", target.url],
        ["Scan ID:", str(scan.id)],
        ["Generated:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Status:", scan.status],
        ["Modules Run:", ", ".join(scan.modules_run)]
    ]
    
    info_table = Table(info_data, colWidths=[2*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f3f4f6')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    
    story.append(info_table)
    story.append(Spacer(1, 20))
    
    # Executive Summary
    if summary:
        story.append(Paragraph("Executive Summary", heading_style))
        story.append(Paragraph(f"<b>Risk Level:</b> {summary.risk_level}", styles['Normal']))
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"<b>Summary:</b> {summary.summary}", styles['Normal']))
        story.append(Spacer(1, 6))
        
        if summary.recommendations:
            story.append(Paragraph("<b>Key Recommendations:</b>", styles['Normal']))
            for rec in summary.recommendations:
                story.append(Paragraph(f"• {rec}", styles['Normal']))
        
        story.append(Spacer(1, 20))
    
    # Findings by Module
    story.append(Paragraph("Detailed Findings", heading_style))
    story.append(Spacer(1, 12))
    
    if findings:
        # Group findings by module
        findings_by_module = {}
        for finding in findings:
            module = finding.module_name
            if module not in findings_by_module:
                findings_by_module[module] = []
            findings_by_module[module].append(finding)
        
        for module, module_findings in findings_by_module.items():
            story.append(Paragraph(f"<b>{module.replace('_', ' ').title()}</b>", styles['Heading3']))
            story.append(Spacer(1, 6))
            
            for finding in module_findings:
                severity_color = {
                    'critical': colors.HexColor('#dc2626'),
                    'high': colors.HexColor('#ea580c'),
                    'medium': colors.HexColor('#ca8a04'),
                    'low': colors.HexColor('#16a34a'),
                    'info': colors.HexColor('#2563eb')
                }.get(finding.severity, colors.black)
                
                finding_text = f"<b>[{finding.severity.upper()}]</b> {finding.title}: {finding.description}"
                story.append(Paragraph(finding_text, styles['Normal']))
                story.append(Spacer(1, 6))
            
            story.append(Spacer(1, 12))
    else:
        story.append(Paragraph("No findings detected.", styles['Normal']))
    
    # Footer
    story.append(Spacer(1, 30))
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.grey,
        alignment=TA_CENTER
    )
    story.append(Paragraph("Generated by Senpai AI - Advanced Security Reconnaissance Platform", footer_style))
    story.append(Paragraph("For authorized testing only. Unauthorized scanning may be illegal.", footer_style))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer
